apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  SECRET_KEY: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
  DATABASE_URL: "postgres://todoapp_user:password@postgres-service:5432/todoapp_db"
  DEBUG: "True"
